import json

import httpx
from sqlalchemy.orm import Session

from app.core.config import get_settings
from app.models.entities import AIGeneratedExplanation, Study
from app.utilities.hashing import canonical_hash


class AIExplanationService:
    prompt_version = "explanation-1.8"
    version_analysis_schema = {
        "type": "object",
        "properties": {
            "executive_summary": {"type": "string"},
            "selected_version_profile": {"type": "array", "items": {"type": "string"}},
            "version_evolution": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "transition": {"type": "string"},
                        "changes": {"type": "array", "items": {"type": "string"}},
                        "interpretation": {"type": "string"},
                    },
                    "required": ["transition", "changes", "interpretation"],
                },
            },
            "research_cautions": {"type": "array", "items": {"type": "string"}},
            "reproducibility_recipe": {"type": "array", "items": {"type": "string"}},
            "potential_effects": {"type": "array", "items": {"type": "string"}},
            "recommended_next_checks": {"type": "array", "items": {"type": "string"}},
            "conclusion": {"type": "string"},
        },
        "required": ["executive_summary", "selected_version_profile", "version_evolution", "research_cautions", "conclusion"],
    }

    def __init__(self, db: Session):
        self.db = db
        self.settings = get_settings()

    def explain(self, study: Study, explanation_type: str, source_entity_id: int, evidence: dict) -> AIGeneratedExplanation:
        if not self.settings.ai_enabled:
            raise ValueError("AI explanations are disabled")
        evidence_hash = canonical_hash(evidence)
        cached = self.db.query(AIGeneratedExplanation).filter(
            AIGeneratedExplanation.study_id == study.id,
            AIGeneratedExplanation.explanation_type == explanation_type,
            AIGeneratedExplanation.source_entity_id == source_entity_id,
            AIGeneratedExplanation.source_evidence_hash == evidence_hash,
            AIGeneratedExplanation.prompt_version == self.prompt_version,
            AIGeneratedExplanation.model == self.settings.ollama_model,
        ).order_by(AIGeneratedExplanation.created_at.desc()).first()
        if cached:
            return cached
        prompt = self._prompt(explanation_type, evidence)
        version_analysis = explanation_type == "version_analysis"
        narrative_interpretation = explanation_type in {"semantic_diff_interpretation", "semantic_metrics", "dataset_executive_summary", "dataset_explanation_report"}
        request_payload = {
            "model": self.settings.ollama_model,
            "prompt": prompt,
            "stream": False,
            "keep_alive": "10m",
            "options": {
                "temperature": 0.25 if narrative_interpretation else 0.1,
                "num_predict": 4096 if version_analysis else 500,
                **({"num_ctx": 16384} if version_analysis else {}),
            },
        }
        if version_analysis:
            request_payload["format"] = self.version_analysis_schema
        content = None
        last_error = None
        timeout = httpx.Timeout(600 if version_analysis else 90, connect=10)
        for _attempt in range(2):
            try:
                response = httpx.post(
                    f"{self.settings.ollama_base_url.rstrip('/')}/api/generate",
                    json=request_payload,
                    timeout=timeout,
                )
                response.raise_for_status()
                content = response.json()["response"].strip()
                if version_analysis:
                    parsed = self._validate_version_analysis(content)
                    parsed["generation_note"] = "Generated by Ollama from the persisted study and dataset evidence."
                    content = json.dumps(parsed, ensure_ascii=False)
                break
            except Exception as exc:
                last_error = exc
        if content is None:
            content = (
                json.dumps(self._fallback_version_analysis(evidence, last_error), ensure_ascii=False)
                if version_analysis
                else self._fallback_interpretation(explanation_type, evidence)
            )
        source_links = {
            "semantic_diff_report_id": source_entity_id if explanation_type in {"semantic_diff", "semantic_metrics", "semantic_diff_interpretation"} else None,
            "profile_report_id": source_entity_id if explanation_type == "profile" else None,
            "diagnosis_report_id": source_entity_id if explanation_type in {"diagnosis", "diagnosis_report_interpretation"} else None,
        }
        record = AIGeneratedExplanation(study_id=study.id, explanation_type=explanation_type, source_entity_type=explanation_type, source_entity_id=source_entity_id, model=self.settings.ollama_model, prompt_version=self.prompt_version, source_evidence_hash=evidence_hash, content=content, **source_links)
        self.db.add(record)
        self.db.commit()
        self.db.refresh(record)
        return record

    @staticmethod
    def _prompt(kind: str, evidence: dict) -> str:
        if kind == "semantic_metrics":
            return (
                "Interpret only these two DATASET VERSION metrics for a research user. "
                "SCM means Semantic Change Magnitude: the amount of structural/content change between dataset versions. "
                "DSI means Distribution Shift Index: the amount of feature/target distribution movement between dataset versions. "
                "These are dataset evidence metrics, not model similarity, not diagnostic similarity, not predictions, and not model performance. "
                "Do not discuss model versions, prediction similarity, accuracy, or training results. Do not start with a generic phrase. "
                "Use exactly two short sections titled SCM and DSI. Explain what each score means for dataset reproducibility and downstream ML caution. "
                "Make the wording specific to the supplied version transition and avoid generic reusable sentences. "
                "Use only supplied evidence and clearly state that these scores alone do not prove model impact. "
                f"Evidence:\n{json.dumps(evidence, default=str)}"
            )
        if kind == "semantic_diff_interpretation":
            return (
                "Act as a senior data-centric ML engineer. Write a smart, human-readable interpretation of this exact dataset-version transition. "
                "Do not dump raw JSON, do not list every metric mechanically, and do not claim model performance was proven. "
                "Do not start with 'Here is', 'This dataset has been updated', or any generic preface. "
                "SCM is Semantic Change Magnitude for dataset-version change. DSI is Distribution Shift Index for dataset distribution movement. "
                "Never describe SCM or DSI as model similarity, diagnostic similarity, predictions, or accuracy. "
                "Focus on the dominant evidence for this transition: schema movement, missingness repair, row-count movement, duplicate movement, numeric drift, categorical drift, or target movement. "
                "Choose natural section titles that fit the evidence. Use exactly 3 short sections. Do not reuse the same titles for every transition unless they are genuinely the best fit. "
                "Each section should be one concise paragraph with concrete nouns from the evidence, such as affected columns, target labels, row movement, or duplicate movement. "
                "Make the next action specific to the observed change. Do not mention a baseline classifier, model architecture, model accuracy, or predictions unless those are explicitly present in the evidence. "
                "Use only supplied evidence and mention exact measured values only when they clarify the interpretation. "
                f"Evidence:\n{json.dumps(evidence, default=str)}"
            )
        if kind == "dataset_executive_summary":
            return (
                "Act as a senior machine learning engineer writing a detailed dataset research summary for one immutable dataset version. "
                "Use the ML study context, selected version identity, configuration, profile summary, semantic diff metrics, version history, and reproducibility evidence. "
                "Return a well-formatted Markdown narrative with clear section headings. Choose section headings dynamically based on the evidence instead of using a fixed template. "
                "Cover the most relevant available topics, such as study purpose, dataset identity, target and evaluation setup, data quality, semantic change, stability, reproducibility, ML training readiness, risks, and next research actions. "
                "Make the explanation specific to the selected dataset version, affected columns, target values, metrics, and observed changes. "
                "When evidence is unavailable, state what is missing and what conclusion cannot be supported yet. "
                "Do not begin with a generic phrase, do not output JSON, and do not list raw evidence mechanically. "
                "Use only supplied evidence. Do not invent metrics, causes, business facts, model results, model performance, or guarantees. "
                f"Evidence:\n{json.dumps(evidence, default=str)}"
            )
        if kind == "dataset_explanation_report":
            return (
                "Create a detailed professional dataset explanation report for a senior machine learning engineer. "
                "Use the study protocol, selected version identity, configuration, profile evidence, semantic differences, diagnosis metrics when present, and reproducibility evidence. "
                "Structure the report with clear headings and concise paragraphs. Explain what the data shows, what changed, what risks or limitations are evidenced, what can be inferred, and what should be done next. "
                "Do not include generic LLM prefaces. Use only supplied evidence. Do not invent metrics, causes, business facts, or model performance. "
                f"Evidence:\n{json.dumps(evidence, default=str)}"
            )
        if kind == "diagnosis_report_interpretation":
            return (
                "Act as a senior data-centric MLOps architect writing a production-grade diagnosis interpretation for one immutable dataset version. "
                "Use only supplied evidence. Do not invent metrics, model results, causes, business facts, or backend behavior. "
                "Do not use generic filler, canned phrases, or raw JSON dumps. Do not say a dataset is safe unless the evidence supports that claim. "
                "Answer the user's practical questions with evidence-bound language: readiness for ML training, leakage risk, stability, data quality, variant-generator implications, and experiment handoff. "
                "Use clear Markdown sections with these exact headings: Executive Diagnosis, ML Training Readiness, Leakage Review, Stability Review, Quality Assessment, Diagnosis Statistics Interpretation, Variant Generator Guidance, Experiment Training Handoff, Supported Claims, Required Next Actions. "
                "Each section must contain specific observations from the evidence and avoid repeating the same sentence structure across sections. "
                "When evidence is unavailable, state the missing evidence and the decision that cannot yet be supported. "
                f"Evidence:\n{json.dumps(evidence, default=str)}"
            )
        if kind == "version_analysis":
            return (
                "Act as a senior data-centric ML researcher writing a detailed evidence review. Do not explain the "
                "JSON structure, list JSON keys, or begin with phrases such as 'This is a JSON object'. Interpret the "
                "actual study and dataset evidence for a human reader. Cover the research objective, selected-version "
                "profile, target/class balance where applicable, missingness, duplicates, notable column statistics, "
                "and every material semantic transition from the baseline through the selected version. Explain what "
                "each observed change may mean for this study, while clearly labeling inference and uncertainty. "
                "Explain what would be required to recreate the selected dataset version from the original CSV and "
                "version bundle evidence. Explain possible downstream effects of schema, missingness, row, duplicate, "
                "and distribution changes only when those changes are present in evidence. "
                "Use only supplied evidence. Do not invent causes, calculate new metrics, change deterministic scores, "
                "claim model performance, or recommend a specific model. Return ONLY valid JSON matching this shape: "
                '{"executive_summary":"detailed paragraph","selected_version_profile":["detailed evidence point"],'
                '"version_evolution":[{"transition":"V1 baseline or V1 to V2","changes":["precise change"],'
                '"interpretation":"careful human-readable interpretation"}],"research_cautions":["evidence-bound caution"],'
                '"reproducibility_recipe":["exact recreation requirement from evidence"],'
                '"potential_effects":["evidence-bound possible downstream effect"],'
                '"recommended_next_checks":["concrete check justified by available evidence"],'
                '"conclusion":"detailed concluding paragraph"}. Include all meaningful evidence; do not stop mid-sentence. '
                f"Evidence:\n{json.dumps(evidence, default=str)}\n"
                "Final instruction: synthesize the evidence into the required insight schema. Never copy or return the "
                "source evidence object. Every top-level field in the required schema must be present and complete."
            )
        return f"You are an evidence-bound data-centric ML research assistant. Explain this {kind} in concise academic language. Use only the supplied JSON. Do not calculate new metrics, change severity, invent findings, or recommend model training. Clearly distinguish evidence from interpretation. Evidence:\n{json.dumps(evidence, default=str)}"

    @classmethod
    def _validate_version_analysis(cls, content: str) -> dict:
        parsed = json.loads(content)
        required = cls.version_analysis_schema["required"]
        if not isinstance(parsed, dict) or any(key not in parsed for key in required):
            raise ValueError("model did not return the required insight sections")
        if not isinstance(parsed["executive_summary"], str) or not isinstance(parsed["conclusion"], str):
            raise ValueError("model returned invalid narrative sections")
        for key in ("selected_version_profile", "version_evolution", "research_cautions"):
            if not isinstance(parsed[key], list):
                raise ValueError(f"model returned invalid {key}")
        for key in ("reproducibility_recipe", "potential_effects", "recommended_next_checks"):
            if key in parsed and not isinstance(parsed[key], list):
                raise ValueError(f"model returned invalid {key}")
        for item in parsed["version_evolution"]:
            if not isinstance(item, dict) or not {"transition", "changes", "interpretation"} <= item.keys():
                raise ValueError("model returned an invalid version evolution entry")
            if not isinstance(item["changes"], list):
                raise ValueError("model returned invalid transition changes")
        return parsed

    @staticmethod
    def _fallback_version_analysis(evidence: dict, error: Exception) -> dict:
        study = evidence.get("ml_study", {})
        dataset = evidence.get("dataset", {})
        selected = evidence.get("selected_version", {})
        profile = evidence.get("dataset_profile", {})
        summary = profile.get("summary", {})
        task_profile = profile.get("task_profile", {})
        columns = profile.get("columns", [])
        objective = study.get("problem_objective") or study.get("description") or "the documented research objective"
        version_number = selected.get("version_number")
        latest_diff = next(
            (
                item.get("semantic_diff_from_previous")
                for item in reversed(evidence.get("version_history", []))
                if item.get("version_number") == version_number and item.get("semantic_diff_from_previous")
            ),
            None,
        )

        profile_points = [
            f"Selected version V{version_number} contains {selected.get('row_count', summary.get('row_count', 0))} rows and {selected.get('column_count', summary.get('column_count', 0))} columns.",
            f"The configured target is {selected.get('target_column') or 'not applicable'}, the primary metric is {selected.get('primary_metric') or 'not applicable'}, and validation uses {selected.get('validation_strategy') or 'not applicable'}.",
            f"The deterministic profile records {summary.get('missing_cells', 0)} missing cells ({float(summary.get('missing_ratio', 0)) * 100:.2f}%) and {summary.get('duplicate_rows', 0)} duplicate rows.",
        ]
        if task_profile.get("class_distribution"):
            distribution = ", ".join(f"{label}: {count}" for label, count in task_profile["class_distribution"].items())
            profile_points.append(
                f"Target classes are distributed as {distribution}; the recorded imbalance ratio is {task_profile.get('imbalance_ratio', 'unavailable')}."
            )
        missing_columns = [
            f"{item.get('name')} ({float(item.get('missing_ratio') or 0) * 100:.2f}%)"
            for item in columns if (item.get("missing_count") or 0) > 0
        ]
        if missing_columns:
            profile_points.append(f"Columns containing missing values are: {', '.join(missing_columns)}.")
        outlier_columns = [
            f"{item.get('name')} ({item.get('outlier_count')} flagged)"
            for item in columns if (item.get("outlier_count") or 0) > 0
        ]
        if outlier_columns:
            profile_points.append(f"Numeric columns with IQR outlier flags are: {', '.join(outlier_columns)}.")

        evolution = []
        for version in evidence.get("version_history", []):
            diff = version.get("semantic_diff_from_previous")
            if not diff:
                evolution.append({
                    "transition": f"V{version.get('version_number')} baseline",
                    "changes": [
                        f"Baseline contains {version.get('row_count')} rows and {version.get('column_count')} columns.",
                        f"Version notes: {version.get('version_notes') or 'No version notes were supplied.'}",
                    ],
                    "interpretation": "This version is the comparison baseline; semantic change cannot be calculated without a predecessor.",
                })
                continue
            changes = [
                f"SCM is {diff.get('scm_score')} and DSI is {diff.get('dsi_score')} under ruleset {diff.get('ruleset_version')}.",
            ]
            schema = diff.get("schema", {})
            if schema.get("columns_added"):
                changes.append(f"Columns added: {', '.join(schema['columns_added'])}.")
            if schema.get("columns_removed"):
                changes.append(f"Columns removed: {', '.join(schema['columns_removed'])}.")
            for column, values in schema.get("data_type_changes", {}).items():
                changes.append(f"{column} changed type from {values.get('previous')} to {values.get('current')}.")
            rows = diff.get("rows", {})
            changes.append(f"Rows changed from {rows.get('previous')} to {rows.get('current')} (net {rows.get('net_change', 0):+}).")
            duplicates = rows.get("duplicate_rows") or {}
            if duplicates:
                changes.append(f"Duplicate rows changed from {duplicates.get('previous')} to {duplicates.get('current')} (net {duplicates.get('delta', 0):+}).")
            for column, values in diff.get("missingness", {}).get("changes_by_column", {}).items():
                changes.append(
                    f"Missing values in {column} changed from {values.get('previous_count')} to {values.get('current_count')} "
                    f"({float(values.get('previous_ratio', 0)) * 100:.2f}% to {float(values.get('current_ratio', 0)) * 100:.2f}%)."
                )
            for column, values in diff.get("numeric_distribution_changes", {}).items():
                previous, current = values.get("previous", {}), values.get("current", {})
                changes.append(
                    f"{column}: mean {previous.get('mean')} → {current.get('mean')}, median {previous.get('median')} → "
                    f"{current.get('median')}, range {previous.get('min')}–{previous.get('max')} → "
                    f"{current.get('min')}–{current.get('max')}, normalized shift {values.get('normalized_shift_score')}."
                )
            for column, values in diff.get("categorical_distribution_changes", {}).items():
                for value in values:
                    changes.append(
                        f"{column}={value.get('value')}: count {value.get('previous_count')} → {value.get('current_count')} "
                        f"and share {float(value.get('previous_ratio', 0)) * 100:.2f}% → {float(value.get('current_ratio', 0)) * 100:.2f}%."
                    )
            evolution.append({
                "transition": f"V{version.get('version_number', 1) - 1} to V{version.get('version_number')}",
                "changes": changes,
                "interpretation": "These are measured dataset changes. Their cause and effect on model performance cannot be established from dataset evidence alone.",
            })

        cautions = [
            "Dataset profile and semantic-difference evidence describe the data; they do not demonstrate model accuracy, fairness, or generalization.",
            "Investigate material target, missingness, schema, and distribution changes before comparing experiments across versions.",
        ]
        if task_profile.get("imbalance_ratio", 1) and float(task_profile.get("imbalance_ratio", 1)) > 1.5:
            cautions.append("The recorded class imbalance can make aggregate performance metrics less representative of minority-class behavior.")
        recipe = []
        for label, value in (
            ("Use the same source file bytes", selected.get("file_hash")),
            ("Use the same combined dataset fingerprint", selected.get("combined_fingerprint")),
            ("Use the same configuration hash", selected.get("configuration_hash")),
            ("Use the same target column", selected.get("target_column")),
            ("Use the same primary metric", selected.get("primary_metric")),
            ("Use the same validation strategy", selected.get("validation_strategy")),
            ("Use the same fingerprint algorithm version", selected.get("fingerprint_algorithm_version")),
        ):
            if value:
                recipe.append(f"{label}: {value}.")
        effects = []
        if latest_diff:
            schema = latest_diff.get("schema", {})
            rows = latest_diff.get("rows", {})
            missingness = latest_diff.get("missingness", {})
            if schema.get("columns_added") or schema.get("columns_removed") or schema.get("data_type_changes"):
                effects.append("Schema changes may alter feature availability or preprocessing compatibility for experiments that reuse an earlier configuration.")
            if rows.get("net_change"):
                effects.append("Row-count changes can shift training, validation, or holdout composition and should be reviewed before comparing experiment results.")
            if missingness.get("overall_ratio_change"):
                effects.append("Missingness changes can alter imputation behavior, retained samples, or feature quality assumptions.")
            if latest_diff.get("numeric_distribution_changes") or latest_diff.get("categorical_distribution_changes"):
                effects.append("Distribution changes may indicate that the selected version is not statistically equivalent to its predecessor.")
            if latest_diff.get("target_distribution_change"):
                effects.append("Target distribution changes can affect metric interpretation, especially for classification studies.")
        checks = [
            "Verify the candidate CSV against the exported recreation bundle before treating it as the same dataset version.",
            "Review the selected version's diagnosis report before promoting it as an experiment baseline.",
        ]
        if latest_diff:
            checks.append("Inspect the semantic comparison against the parent version and document whether the change is intentional.")
        return {
            "executive_summary": (
                f"This evidence review covers {dataset.get('name', 'the dataset')} through V{version_number} for the "
                f"{study.get('name', 'ML study')} ({study.get('ml_task', 'ML task')}). The study seeks to address "
                f"{objective}. The summary below is generated directly from persisted deterministic evidence."
            ),
            "selected_version_profile": profile_points,
            "version_evolution": evolution,
            "research_cautions": cautions,
            "reproducibility_recipe": recipe,
            "potential_effects": effects,
            "recommended_next_checks": checks,
            "conclusion": (
                f"V{version_number} is fully documented against its preceding versions. Use the listed profile and "
                "transition evidence to decide whether versions remain comparable research conditions; model impact "
                "requires separate controlled experiments."
            ),
            "generation_note": f"Ollama could not complete a valid structured response, so the complete deterministic evidence summary is shown instead ({type(error).__name__}).",
        }

    @staticmethod
    def _fallback_interpretation(kind: str, evidence: dict) -> str:
        rows = []
        if kind in {"semantic_metrics", "semantic_diff_interpretation", "semantic_diff"}:
            rows.append("Interpretation temporarily unavailable. The measured semantic evidence remains available.")
            if evidence.get("scm_score") is not None:
                rows.append(f"SCM: {evidence.get('scm_score')}.")
            if evidence.get("dsi_score") is not None:
                rows.append(f"DSI: {evidence.get('dsi_score')}.")
            report = evidence.get("semantic_diff") or evidence.get("report") or {}
            schema = report.get("schema") or report
            added = schema.get("columns_added") or []
            removed = schema.get("columns_removed") or []
            if added:
                rows.append(f"Columns added: {', '.join(map(str, added))}.")
            if removed:
                rows.append(f"Columns removed: {', '.join(map(str, removed))}.")
            return "\n".join(rows)
        if kind in {"diagnosis", "diagnosis_report_interpretation"}:
            diagnosis = evidence.get("diagnosis") or evidence
            rows.append("Interpretation temporarily unavailable. The deterministic diagnosis remains available.")
            if diagnosis.get("mlrs_score") is not None:
                rows.append(f"MLRS: {diagnosis.get('mlrs_score')}.")
            if diagnosis.get("lrs_score") is not None:
                rows.append(f"LRS: {diagnosis.get('lrs_score')}.")
            findings = diagnosis.get("findings") or []
            if findings:
                rows.append("Detected findings: " + ", ".join(str(item.get("code") or item.get("issue")) for item in findings[:6]) + ".")
            return "\n".join(rows)
        if kind in {"dataset_executive_summary", "dataset_explanation_report", "version_analysis"}:
            selected = evidence.get("selected_version") or {}
            rows.append("Interpretation temporarily unavailable. The persisted version evidence remains available.")
            if selected:
                rows.append(f"Selected version: V{selected.get('version_number')} with {selected.get('row_count')} rows and {selected.get('column_count')} columns.")
            return "\n".join(rows)
        return "Interpretation temporarily unavailable. The measured evidence remains available below."
