import json
from collections.abc import Iterator

import httpx
from sqlalchemy.orm import Session

from app.core.config import get_settings
from app.models.entities import AIGeneratedExplanation, Study
from app.utilities.hashing import canonical_hash


class AIExplanationService:
    prompt_version = "explanation-2.1"
    version_analysis_schema = {
        "type": "object",
        "properties": {
            "executive_summary": {"type": "string"},
            "selected_version_profile": {"type": "array", "items": {"type": "string"}},
            "version_evolution": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "transition": {"type": "string"},
                        "changes": {"type": "array", "items": {"type": "string"}},
                        "interpretation": {"type": "string"},
                    },
                    "required": ["transition", "changes", "interpretation"],
                },
            },
            "research_cautions": {"type": "array", "items": {"type": "string"}},
            "reproducibility_recipe": {"type": "array", "items": {"type": "string"}},
            "potential_effects": {"type": "array", "items": {"type": "string"}},
            "recommended_next_checks": {"type": "array", "items": {"type": "string"}},
            "conclusion": {"type": "string"},
        },
        "required": ["executive_summary", "selected_version_profile", "version_evolution", "research_cautions", "conclusion"],
    }

    def __init__(self, db: Session, model: str | None = None):
        self.db = db
        self.settings = get_settings()
        self.model = model or self.settings.ollama_model

    def explain(self, study: Study, explanation_type: str, source_entity_id: int, evidence: dict) -> AIGeneratedExplanation:
        if not self.settings.ai_enabled:
            raise ValueError("AI explanations are disabled")
        evidence_hash = canonical_hash(evidence)
        cached = self.db.query(AIGeneratedExplanation).filter(
            AIGeneratedExplanation.study_id == study.id,
            AIGeneratedExplanation.explanation_type == explanation_type,
            AIGeneratedExplanation.source_entity_id == source_entity_id,
            AIGeneratedExplanation.source_evidence_hash == evidence_hash,
            AIGeneratedExplanation.prompt_version == self.prompt_version,
            AIGeneratedExplanation.model == self.model,
        ).order_by(AIGeneratedExplanation.created_at.desc()).first()
        if cached and not self.is_fallback_content(cached.content):
            return cached
        prompt = self._prompt(explanation_type, evidence)
        version_analysis = explanation_type == "version_analysis"
        request_payload = self._request_payload(explanation_type, prompt, stream=False)
        if version_analysis:
            request_payload["format"] = self.version_analysis_schema
        content = None
        last_error = None
        timeout = self._timeout(explanation_type)
        max_attempts = self._max_attempts(explanation_type)
        for _attempt in range(max_attempts):
            try:
                response = httpx.post(
                    f"{self.settings.ollama_base_url.rstrip('/')}/api/generate",
                    json=request_payload,
                    timeout=timeout,
                )
                response.raise_for_status()
                content = response.json()["response"].strip()
                if not content:
                    raise ValueError("Ollama returned an empty response")
                if version_analysis:
                    parsed = self._validate_version_analysis(content)
                    parsed["generation_note"] = "Generated by Ollama from the persisted study and dataset evidence."
                    content = json.dumps(parsed, ensure_ascii=False)
                break
            except Exception as exc:
                last_error = exc
        if content is None:
            content = (
                json.dumps(self._fallback_version_analysis(evidence, last_error), ensure_ascii=False)
                if version_analysis
                else self._fallback_interpretation(explanation_type, evidence)
            )
        source_links = {
            "semantic_diff_report_id": source_entity_id if explanation_type in {"semantic_diff", "semantic_metrics", "semantic_diff_interpretation"} else None,
            "profile_report_id": source_entity_id if explanation_type == "profile" else None,
            "diagnosis_report_id": source_entity_id if explanation_type in {"diagnosis", "diagnosis_report_interpretation"} else None,
        }
        record = AIGeneratedExplanation(study_id=study.id, explanation_type=explanation_type, source_entity_type=explanation_type, source_entity_id=source_entity_id, model=self.model, prompt_version=self.prompt_version, source_evidence_hash=evidence_hash, content=content, **source_links)
        self.db.add(record)
        self.db.commit()
        self.db.refresh(record)
        return record

    def explain_stream(self, study: Study, explanation_type: str, source_entity_id: int, evidence: dict) -> Iterator[str]:
        if not self.settings.ai_enabled:
            raise ValueError("AI explanations are disabled")
        evidence_hash = canonical_hash(evidence)
        cached = self.db.query(AIGeneratedExplanation).filter(
            AIGeneratedExplanation.study_id == study.id,
            AIGeneratedExplanation.explanation_type == explanation_type,
            AIGeneratedExplanation.source_entity_id == source_entity_id,
            AIGeneratedExplanation.source_evidence_hash == evidence_hash,
            AIGeneratedExplanation.prompt_version == self.prompt_version,
            AIGeneratedExplanation.model == self.model,
        ).order_by(AIGeneratedExplanation.created_at.desc()).first()
        if cached and not self.is_fallback_content(cached.content):
            yield cached.content
            return

        prompt = self._prompt(explanation_type, evidence)
        request_payload = self._request_payload(explanation_type, prompt, stream=True)
        chunks = []
        last_error = None
        try:
            with httpx.stream(
                "POST",
                f"{self.settings.ollama_base_url.rstrip('/')}/api/generate",
                json=request_payload,
                timeout=self._timeout(explanation_type),
            ) as response:
                response.raise_for_status()
                for line in response.iter_lines():
                    if not line:
                        continue
                    payload = json.loads(line)
                    chunk = payload.get("response", "")
                    if chunk:
                        chunks.append(chunk)
                        yield chunk
                    if payload.get("done"):
                        break
        except Exception as exc:
            last_error = exc

        content = "".join(chunks).strip()
        if not content:
            content = self._fallback_interpretation(explanation_type, evidence)
            yield content

        record = AIGeneratedExplanation(
            study_id=study.id,
            explanation_type=explanation_type,
            source_entity_type=explanation_type,
            source_entity_id=source_entity_id,
            model=self.model,
            prompt_version=self.prompt_version,
            source_evidence_hash=evidence_hash,
            content=content,
        )
        self.db.add(record)
        self.db.commit()

    def _request_payload(self, explanation_type: str, prompt: str, stream: bool) -> dict:
        version_analysis = explanation_type == "version_analysis"
        executive_summary = explanation_type == "dataset_executive_summary"
        narrative_interpretation = explanation_type in {"semantic_diff_interpretation", "semantic_metrics", "dataset_executive_summary", "dataset_explanation_report", "diagnosis_report_interpretation"}
        return {
            "model": self.model,
            "prompt": prompt,
            "stream": stream,
            "keep_alive": "10m",
            "options": {
                "temperature": 0.25 if narrative_interpretation else 0.1,
                "num_predict": self.settings.ai_version_analysis_max_tokens if version_analysis else self.settings.ai_report_max_tokens if narrative_interpretation else 900,
                **({"num_ctx": 16384} if version_analysis else {}),
            },
        }

    def _timeout(self, explanation_type: str) -> httpx.Timeout:
        if explanation_type == "version_analysis":
            return httpx.Timeout(self.settings.ai_job_timeout_seconds, connect=10)
        if explanation_type == "dataset_executive_summary":
            return httpx.Timeout(180, connect=10, read=180)
        return httpx.Timeout(90, connect=10)

    def _max_attempts(self, explanation_type: str) -> int:
        return self.settings.ai_job_max_attempts if explanation_type == "version_analysis" else 1 if explanation_type == "dataset_executive_summary" else 2

    @staticmethod
    def _prompt(kind: str, evidence: dict) -> str:
        if kind == "semantic_metrics":
            return (
                "Act as a senior data-centric ML engineer interpreting these DATASET VERSION metrics for a research review. "
                "SCM means Semantic Change Magnitude: the amount of structural/content change between dataset versions. "
                "DSI means Distribution Shift Index: the amount of feature/target distribution movement between dataset versions. "
                "These are dataset evidence metrics, not model similarity, not diagnostic similarity, not predictions, and not model performance. "
                "Do not discuss model versions, prediction similarity, accuracy, or training results. Do not start with a generic phrase. "
                "Use clear Markdown sections titled SCM and DSI. Explain what each score means for dataset reproducibility, downstream ML caution, experiment comparability, and required review before training. "
                "Make the wording specific to the supplied version transition and avoid generic reusable sentences. "
                "Use only supplied evidence and clearly state that these scores alone do not prove model impact. Provide detailed reasoning, not a small summary. "
                f"Evidence:\n{json.dumps(evidence, default=str)}"
            )
        if kind == "semantic_diff_interpretation":
            return (
                "Act as a senior data-centric ML engineer. Write a smart, human-readable interpretation of this exact dataset-version transition. "
                "Do not dump raw JSON, do not list every metric mechanically, and do not claim model performance was proven. "
                "Do not start with 'Here is', 'This dataset has been updated', or any generic preface. "
                "SCM is Semantic Change Magnitude for dataset-version change. DSI is Distribution Shift Index for dataset distribution movement. "
                "Never describe SCM or DSI as model similarity, diagnostic similarity, predictions, or accuracy. "
                "Focus on the dominant evidence for this transition: schema movement, missingness repair, row-count movement, duplicate movement, numeric drift, categorical drift, or target movement. "
                "Choose natural section titles that fit the evidence. Use exactly 3 short sections. Do not reuse the same titles for every transition unless they are genuinely the best fit. "
                "Each section should be one concise paragraph with concrete nouns from the evidence, such as affected columns, target labels, row movement, or duplicate movement. "
                "Make the next action specific to the observed change. Do not mention a baseline classifier, model architecture, model accuracy, or predictions unless those are explicitly present in the evidence. "
                "Use only supplied evidence and mention exact measured values only when they clarify the interpretation. "
                f"Evidence:\n{json.dumps(evidence, default=str)}"
            )
        if kind == "dataset_executive_summary":
            evidence = AIExplanationService._compact_executive_summary_evidence(evidence)
            return (
                "Act as a senior machine learning engineer writing a detailed dataset research summary for one immutable dataset version. "
                "Return well-formatted Markdown with clear section headings. Cover study purpose, dataset identity, target/evaluation setup, "
                "data quality, semantic version change, reproducibility, ML training readiness, risks, and next research actions. "
                "Make the explanation specific to the selected version, affected columns, target values, metrics, and observed changes. "
                "Write in a senior-review style with enough depth to explain why each risk, limitation, or readiness claim follows from the evidence. "
                "Do not output JSON, do not begin with a generic preface, and do not invent model results, causes, business facts, or guarantees. "
                f"Evidence:\n{json.dumps(evidence, default=str)}"
            )
        if kind == "dataset_explanation_report":
            return (
                "Create a detailed professional dataset explanation report for a senior machine learning engineer. "
                "Use the study protocol, selected version identity, configuration, profile evidence, semantic differences, diagnosis metrics when present, and reproducibility evidence. "
                "Structure the report with clear headings and concise paragraphs. Explain what the data shows, what changed, what risks or limitations are evidenced, what can be inferred, and what should be done next. "
                "Do not include generic LLM prefaces. Use only supplied evidence. Do not invent metrics, causes, business facts, or model performance. "
                f"Evidence:\n{json.dumps(evidence, default=str)}"
            )
        if kind == "diagnosis_report_interpretation":
            return (
                "Act as a senior data-centric MLOps architect writing a production-grade diagnosis interpretation for one immutable dataset version. "
                "Use only supplied evidence. Do not invent metrics, model results, causes, business facts, or backend behavior. "
                "Do not use generic filler, canned phrases, or raw JSON dumps. Do not say a dataset is safe unless the evidence supports that claim. "
                "Answer the user's practical questions with evidence-bound language: readiness for ML training, leakage risk, stability, data quality, variant-generator implications, and experiment handoff. "
                "Use clear Markdown sections with these exact headings: Executive Diagnosis, ML Training Readiness, Leakage Review, Stability Review, Quality Assessment, Diagnosis Statistics Interpretation, Variant Generator Guidance, Experiment Training Handoff, Supported Claims, Required Next Actions. "
                "Each section must contain specific observations from the evidence and explain why those observations matter to a senior ML engineer. "
                "Do not make sections tiny. Prefer complete paragraphs with concrete evidence, implications, and limitations. "
                "When evidence is unavailable, state the missing evidence and the decision that cannot yet be supported. "
                f"Evidence:\n{json.dumps(evidence, default=str)}"
            )
        if kind == "version_analysis":
            return (
                "Act as a senior data-centric ML researcher writing a detailed evidence review. Do not explain the "
                "JSON structure, list JSON keys, or begin with phrases such as 'This is a JSON object'. Interpret the "
                "actual study and dataset evidence for a human reader. Cover the research objective, selected-version "
                "profile, target/class balance where applicable, missingness, duplicates, notable column statistics, "
                "and every material semantic transition from the baseline through the selected version. Explain what "
                "each observed change may mean for this study, while clearly labeling inference and uncertainty. "
                "Explain what would be required to recreate the selected dataset version from the original CSV and "
                "version bundle evidence. Explain possible downstream effects of schema, missingness, row, duplicate, "
                "and distribution changes only when those changes are present in evidence. "
                "Use only supplied evidence. Do not invent causes, calculate new metrics, change deterministic scores, "
                "claim model performance, or recommend a specific model. Return ONLY valid JSON matching this shape: "
                '{"executive_summary":"detailed paragraph","selected_version_profile":["detailed evidence point"],'
                '"version_evolution":[{"transition":"V1 baseline or V1 to V2","changes":["precise change"],'
                '"interpretation":"careful human-readable interpretation"}],"research_cautions":["evidence-bound caution"],'
                '"reproducibility_recipe":["exact recreation requirement from evidence"],'
                '"potential_effects":["evidence-bound possible downstream effect"],'
                '"recommended_next_checks":["concrete check justified by available evidence"],'
                '"conclusion":"detailed concluding paragraph"}. Include all meaningful evidence; do not stop mid-sentence. '
                f"Evidence:\n{json.dumps(evidence, default=str)}\n"
                "Final instruction: synthesize the evidence into the required insight schema. Never copy or return the "
                "source evidence object. Every top-level field in the required schema must be present and complete."
            )
        return f"You are an evidence-bound data-centric ML research assistant. Explain this {kind} in concise academic language. Use only the supplied JSON. Do not calculate new metrics, change severity, invent findings, or recommend model training. Clearly distinguish evidence from interpretation. Evidence:\n{json.dumps(evidence, default=str)}"

    @classmethod
    def _validate_version_analysis(cls, content: str) -> dict:
        parsed = json.loads(content)
        required = cls.version_analysis_schema["required"]
        if not isinstance(parsed, dict) or any(key not in parsed for key in required):
            raise ValueError("model did not return the required insight sections")
        if not isinstance(parsed["executive_summary"], str) or not isinstance(parsed["conclusion"], str):
            raise ValueError("model returned invalid narrative sections")
        for key in ("selected_version_profile", "version_evolution", "research_cautions"):
            if not isinstance(parsed[key], list):
                raise ValueError(f"model returned invalid {key}")
        for key in ("reproducibility_recipe", "potential_effects", "recommended_next_checks"):
            if key in parsed and not isinstance(parsed[key], list):
                raise ValueError(f"model returned invalid {key}")
        for item in parsed["version_evolution"]:
            if not isinstance(item, dict) or not {"transition", "changes", "interpretation"} <= item.keys():
                raise ValueError("model returned an invalid version evolution entry")
            if not isinstance(item["changes"], list):
                raise ValueError("model returned invalid transition changes")
        return parsed

    @staticmethod
    def _compact_executive_summary_evidence(evidence: dict) -> dict:
        selected = evidence.get("selected_version") or {}
        profile = evidence.get("dataset_profile") or {}
        summary = profile.get("summary") or {}
        task_profile = profile.get("task_profile") or {}
        columns = profile.get("columns") or []
        current_version_number = selected.get("version_number")
        current_history = next(
            (
                item for item in reversed(evidence.get("version_history") or [])
                if item.get("version_number") == current_version_number
            ),
            {},
        )
        diff = current_history.get("semantic_diff_from_previous") or {}
        missing_columns = [
            {"name": item.get("name"), "missing_count": item.get("missing_count"), "missing_ratio": item.get("missing_ratio")}
            for item in columns
            if (item.get("missing_count") or 0) > 0
        ][:5]
        outlier_columns = [
            {"name": item.get("name"), "outlier_count": item.get("outlier_count")}
            for item in columns
            if (item.get("outlier_count") or 0) > 0
        ][:5]
        return {
            "ml_study": evidence.get("ml_study"),
            "dataset": evidence.get("dataset"),
            "selected_version": selected,
            "profile_summary": summary,
            "target_profile": {
                "class_distribution": task_profile.get("class_distribution"),
                "imbalance_ratio": task_profile.get("imbalance_ratio"),
            },
            "notable_columns": {
                "missing": missing_columns,
                "outliers": outlier_columns,
            },
            "current_version_change": {
                "scm_score": diff.get("scm_score"),
                "dsi_score": diff.get("dsi_score"),
                "columns_added": (diff.get("schema") or {}).get("columns_added"),
                "columns_removed": (diff.get("schema") or {}).get("columns_removed"),
                "rows": diff.get("rows"),
                "missingness": diff.get("missingness"),
                "target_distribution_change": diff.get("target_distribution_change"),
            } if diff else None,
        }

    @staticmethod
    def is_fallback_content(content: str | None) -> bool:
        if not content:
            return False
        stripped = content.lstrip()
        if stripped.startswith("Interpretation temporarily unavailable."):
            return True
        try:
            parsed = json.loads(stripped)
        except json.JSONDecodeError:
            return False
        if not isinstance(parsed, dict):
            return False
        return str(parsed.get("generation_note", "")).startswith("Ollama could not")

    @staticmethod
    def _fallback_version_analysis(evidence: dict, error: Exception) -> dict:
        study = evidence.get("ml_study", {})
        dataset = evidence.get("dataset", {})
        selected = evidence.get("selected_version", {})
        profile = evidence.get("dataset_profile", {})
        summary = profile.get("summary", {})
        task_profile = profile.get("task_profile", {})
        columns = profile.get("columns", [])
        objective = study.get("problem_objective") or study.get("description") or "the documented research objective"
        version_number = selected.get("version_number")
        latest_diff = next(
            (
                item.get("semantic_diff_from_previous")
                for item in reversed(evidence.get("version_history", []))
                if item.get("version_number") == version_number and item.get("semantic_diff_from_previous")
            ),
            None,
        )

        profile_points = [
            f"Selected version V{version_number} contains {selected.get('row_count', summary.get('row_count', 0))} rows and {selected.get('column_count', summary.get('column_count', 0))} columns.",
            f"The configured target is {selected.get('target_column') or 'not applicable'}, the primary metric is {selected.get('primary_metric') or 'not applicable'}, and validation uses {selected.get('validation_strategy') or 'not applicable'}.",
            f"The deterministic profile records {summary.get('missing_cells', 0)} missing cells ({float(summary.get('missing_ratio', 0)) * 100:.2f}%) and {summary.get('duplicate_rows', 0)} duplicate rows.",
        ]
        if task_profile.get("class_distribution"):
            distribution = ", ".join(f"{label}: {count}" for label, count in task_profile["class_distribution"].items())
            profile_points.append(
                f"Target classes are distributed as {distribution}; the recorded imbalance ratio is {task_profile.get('imbalance_ratio', 'unavailable')}."
            )
        missing_columns = [
            f"{item.get('name')} ({float(item.get('missing_ratio') or 0) * 100:.2f}%)"
            for item in columns if (item.get("missing_count") or 0) > 0
        ]
        if missing_columns:
            profile_points.append(f"Columns containing missing values are: {', '.join(missing_columns)}.")
        outlier_columns = [
            f"{item.get('name')} ({item.get('outlier_count')} flagged)"
            for item in columns if (item.get("outlier_count") or 0) > 0
        ]
        if outlier_columns:
            profile_points.append(f"Numeric columns with IQR outlier flags are: {', '.join(outlier_columns)}.")

        evolution = []
        for version in evidence.get("version_history", []):
            diff = version.get("semantic_diff_from_previous")
            if not diff:
                evolution.append({
                    "transition": f"V{version.get('version_number')} baseline",
                    "changes": [
                        f"Baseline contains {version.get('row_count')} rows and {version.get('column_count')} columns.",
                        f"Version notes: {version.get('version_notes') or 'No version notes were supplied.'}",
                    ],
                    "interpretation": "This version is the comparison baseline; semantic change cannot be calculated without a predecessor.",
                })
                continue
            changes = [
                f"SCM is {diff.get('scm_score')} and DSI is {diff.get('dsi_score')} under ruleset {diff.get('ruleset_version')}.",
            ]
            schema = diff.get("schema", {})
            if schema.get("columns_added"):
                changes.append(f"Columns added: {', '.join(schema['columns_added'])}.")
            if schema.get("columns_removed"):
                changes.append(f"Columns removed: {', '.join(schema['columns_removed'])}.")
            for column, values in schema.get("data_type_changes", {}).items():
                changes.append(f"{column} changed type from {values.get('previous')} to {values.get('current')}.")
            rows = diff.get("rows", {})
            changes.append(f"Rows changed from {rows.get('previous')} to {rows.get('current')} (net {rows.get('net_change', 0):+}).")
            duplicates = rows.get("duplicate_rows") or {}
            if duplicates:
                changes.append(f"Duplicate rows changed from {duplicates.get('previous')} to {duplicates.get('current')} (net {duplicates.get('delta', 0):+}).")
            for column, values in diff.get("missingness", {}).get("changes_by_column", {}).items():
                changes.append(
                    f"Missing values in {column} changed from {values.get('previous_count')} to {values.get('current_count')} "
                    f"({float(values.get('previous_ratio', 0)) * 100:.2f}% to {float(values.get('current_ratio', 0)) * 100:.2f}%)."
                )
            for column, values in diff.get("numeric_distribution_changes", {}).items():
                previous, current = values.get("previous", {}), values.get("current", {})
                changes.append(
                    f"{column}: mean {previous.get('mean')} → {current.get('mean')}, median {previous.get('median')} → "
                    f"{current.get('median')}, range {previous.get('min')}–{previous.get('max')} → "
                    f"{current.get('min')}–{current.get('max')}, normalized shift {values.get('normalized_shift_score')}."
                )
            for column, values in diff.get("categorical_distribution_changes", {}).items():
                for value in values:
                    changes.append(
                        f"{column}={value.get('value')}: count {value.get('previous_count')} → {value.get('current_count')} "
                        f"and share {float(value.get('previous_ratio', 0)) * 100:.2f}% → {float(value.get('current_ratio', 0)) * 100:.2f}%."
                    )
            evolution.append({
                "transition": f"V{version.get('version_number', 1) - 1} to V{version.get('version_number')}",
                "changes": changes,
                "interpretation": "These are measured dataset changes. Their cause and effect on model performance cannot be established from dataset evidence alone.",
            })

        cautions = [
            "Dataset profile and semantic-difference evidence describe the data; they do not demonstrate model accuracy, fairness, or generalization.",
            "Investigate material target, missingness, schema, and distribution changes before comparing experiments across versions.",
        ]
        if task_profile.get("imbalance_ratio", 1) and float(task_profile.get("imbalance_ratio", 1)) > 1.5:
            cautions.append("The recorded class imbalance can make aggregate performance metrics less representative of minority-class behavior.")
        recipe = []
        for label, value in (
            ("Use the same source file bytes", selected.get("file_hash")),
            ("Use the same combined dataset fingerprint", selected.get("combined_fingerprint")),
            ("Use the same configuration hash", selected.get("configuration_hash")),
            ("Use the same target column", selected.get("target_column")),
            ("Use the same primary metric", selected.get("primary_metric")),
            ("Use the same validation strategy", selected.get("validation_strategy")),
            ("Use the same fingerprint algorithm version", selected.get("fingerprint_algorithm_version")),
        ):
            if value:
                recipe.append(f"{label}: {value}.")
        effects = []
        if latest_diff:
            schema = latest_diff.get("schema", {})
            rows = latest_diff.get("rows", {})
            missingness = latest_diff.get("missingness", {})
            if schema.get("columns_added") or schema.get("columns_removed") or schema.get("data_type_changes"):
                effects.append("Schema changes may alter feature availability or preprocessing compatibility for experiments that reuse an earlier configuration.")
            if rows.get("net_change"):
                effects.append("Row-count changes can shift training, validation, or holdout composition and should be reviewed before comparing experiment results.")
            if missingness.get("overall_ratio_change"):
                effects.append("Missingness changes can alter imputation behavior, retained samples, or feature quality assumptions.")
            if latest_diff.get("numeric_distribution_changes") or latest_diff.get("categorical_distribution_changes"):
                effects.append("Distribution changes may indicate that the selected version is not statistically equivalent to its predecessor.")
            if latest_diff.get("target_distribution_change"):
                effects.append("Target distribution changes can affect metric interpretation, especially for classification studies.")
        checks = [
            "Verify the candidate CSV against the exported recreation bundle before treating it as the same dataset version.",
            "Review the selected version's diagnosis report before promoting it as an experiment baseline.",
        ]
        if latest_diff:
            checks.append("Inspect the semantic comparison against the parent version and document whether the change is intentional.")
        return {
            "executive_summary": (
                f"This evidence review covers {dataset.get('name', 'the dataset')} through V{version_number} for the "
                f"{study.get('name', 'ML study')} ({study.get('ml_task', 'ML task')}). The study seeks to address "
                f"{objective}. The summary below is generated directly from persisted deterministic evidence."
            ),
            "selected_version_profile": profile_points,
            "version_evolution": evolution,
            "research_cautions": cautions,
            "reproducibility_recipe": recipe,
            "potential_effects": effects,
            "recommended_next_checks": checks,
            "conclusion": (
                f"V{version_number} is fully documented against its preceding versions. Use the listed profile and "
                "transition evidence to decide whether versions remain comparable research conditions; model impact "
                "requires separate controlled experiments."
            ),
            "generation_note": f"Ollama could not complete a valid structured response, so the complete deterministic evidence summary is shown instead ({type(error).__name__}).",
        }

    @staticmethod
    def _fallback_interpretation(kind: str, evidence: dict) -> str:
        rows = []
        if kind in {"semantic_metrics", "semantic_diff_interpretation", "semantic_diff"}:
            rows.append("Interpretation temporarily unavailable. The measured semantic evidence remains available.")
            if evidence.get("scm_score") is not None:
                rows.append(f"SCM: {evidence.get('scm_score')}.")
            if evidence.get("dsi_score") is not None:
                rows.append(f"DSI: {evidence.get('dsi_score')}.")
            report = evidence.get("semantic_diff") or evidence.get("report") or {}
            schema = report.get("schema") or report
            added = schema.get("columns_added") or []
            removed = schema.get("columns_removed") or []
            if added:
                rows.append(f"Columns added: {', '.join(map(str, added))}.")
            if removed:
                rows.append(f"Columns removed: {', '.join(map(str, removed))}.")
            return "\n".join(rows)
        if kind in {"diagnosis", "diagnosis_report_interpretation"}:
            return AIExplanationService._deterministic_diagnosis_interpretation(evidence)
        if kind in {"dataset_executive_summary", "dataset_explanation_report", "version_analysis"}:
            selected = evidence.get("selected_version") or {}
            rows.append("Interpretation temporarily unavailable. The persisted version evidence remains available.")
            if selected:
                rows.append(f"Selected version: V{selected.get('version_number')} with {selected.get('row_count')} rows and {selected.get('column_count')} columns.")
            return "\n".join(rows)
        return "Interpretation temporarily unavailable. The measured evidence remains available below."

    @staticmethod
    def _deterministic_diagnosis_interpretation(evidence: dict) -> str:
        study = evidence.get("ml_study") or {}
        selected = evidence.get("selected_version") or {}
        profile = evidence.get("dataset_profile") or {}
        summary = profile.get("summary") or {}
        diagnosis = evidence.get("diagnosis") or evidence
        contract = evidence.get("diagnosis_contract") or {}
        readiness = contract.get("readiness") or {}
        semantic = evidence.get("semantic_diff_from_previous")
        findings = diagnosis.get("findings") or []
        families = contract.get("risk_families") or []
        interventions = contract.get("intervention_options") or []
        decisions = contract.get("human_decisions") or []
        score_breakdown = diagnosis.get("score_breakdown") or {}
        mlrs_components = score_breakdown.get("mlrs_components") or {}
        lrs_components = score_breakdown.get("lrs_components") or {}

        def metric(value, default="not available"):
            return default if value is None else str(value)

        def list_text(values, default="None recorded"):
            values = [str(item) for item in values if item not in (None, "")]
            return ", ".join(values) if values else default

        def columns_for_finding(finding):
            evidence_json = finding.get("evidence") or {}
            columns = []
            for item in evidence_json.get("columns") or []:
                columns.append(str(item.get("column") if isinstance(item, dict) else item))
            if evidence_json.get("target_column"):
                columns.append(str(evidence_json["target_column"]))
            for key in ("correlations", "pairs"):
                for item in evidence_json.get(key) or []:
                    if isinstance(item, dict):
                        columns.extend([str(item.get("left")), str(item.get("right"))])
            return sorted({item for item in columns if item and item != "None"})

        finding_lines = []
        for finding in findings[:10]:
            code = finding.get("code") or "finding"
            issue = finding.get("issue") or "Diagnosis finding"
            severity = finding.get("severity") or "unclassified"
            columns = columns_for_finding(finding)
            risk = finding.get("risk") or "No risk statement recorded."
            recommendation = finding.get("recommendation") or "No recommendation recorded."
            finding_lines.append(
                f"- **{code} ({severity})**: {issue}. Scope: {list_text(columns, 'dataset-level evidence')}. Risk: {risk} Recommendation: {recommendation}"
            )
        if not finding_lines:
            finding_lines.append("- No material deterministic finding crossed the configured diagnosis thresholds.")

        component_lines = []
        for title, components in (("MLRS components", mlrs_components), ("LRS components", lrs_components)):
            active = [(key.replace("_", " "), value) for key, value in components.items() if value not in (None, 0, 0.0)]
            if active:
                component_lines.append(f"- **{title}**: " + "; ".join(f"{key}: {value}" for key, value in active[:8]) + ".")
            else:
                component_lines.append(f"- **{title}**: no component contribution was recorded above zero.")

        family_lines = []
        for family in families[:8]:
            affected = family.get("affected_columns") or []
            family_lines.append(
                f"- **{family.get('family', 'risk family')} ({family.get('severity', 'unclassified')})**: {family.get('finding_count', 0)} finding(s), affected scope: {list_text(affected, 'dataset-level')}."
            )
        if not family_lines:
            family_lines.append("- No grouped risk-family contract evidence was recorded.")

        intervention_lines = []
        for option in interventions[:8]:
            ops = [str(op.get("operation", "")).replace("_", " ") for op in option.get("operations") or []]
            intervention_lines.append(
                f"- **{option.get('title', 'Intervention option')}**: {option.get('objective', 'No objective recorded')} Operations: {list_text(ops, 'no operations recorded')}. Expected changes: {list_text(option.get('expected_changes') or [])}."
            )
        if not intervention_lines:
            intervention_lines.append("- No intervention options were generated from the current diagnosis.")

        decision_lines = []
        for decision in decisions[:8]:
            decision_lines.append(
                f"- **{decision.get('question', 'Decision required')}** Default: {decision.get('recommended_default', 'not recorded')}. Scope: {list_text(decision.get('affected_columns') or [], 'dataset-level')}."
            )
        if not decision_lines:
            decision_lines.append("- No human approval gates are required by the current diagnosis contract.")

        stability_text = (
            f"Semantic comparison is available with SCM {metric(semantic.get('scm_score'))} and DSI {metric(semantic.get('dsi_score'))}."
            if isinstance(semantic, dict)
            else "No semantic comparison evidence is attached for this version, so stability against a predecessor cannot be interpreted from this report."
        )

        return "\n\n".join([
            "# Executive Diagnosis",
            (
                f"This stored diagnosis report covers study **{study.get('name', 'Untitled study')}**, version "
                f"**V{metric(selected.get('version_number'))}**, with {metric(selected.get('row_count'))} rows and "
                f"{metric(selected.get('column_count'))} columns. The deterministic diagnosis recorded MLRS "
                f"**{metric(diagnosis.get('mlrs_score'))}** and LRS **{metric(diagnosis.get('lrs_score'))}** under "
                f"ruleset **{diagnosis.get('ruleset_version', 'not available')}**. Readiness status from the diagnosis contract is "
                f"**{readiness.get('status', 'not available')}**."
            ),
            "# ML Training Readiness",
            (
                f"MLRS is the machine-learning readiness risk score, where lower is better. The current value is "
                f"**{metric(diagnosis.get('mlrs_score'))}**. The profile summary reports {metric(summary.get('missing_cells'), '0')} missing cells, "
                f"{metric(summary.get('duplicate_rows'), '0')} duplicate rows, and {metric(summary.get('numeric_columns'))} numeric / "
                f"{metric(summary.get('categorical_columns'))} categorical columns. These are the main readiness signals available in stored evidence."
            ),
            "\n".join(component_lines),
            "# Leakage Review",
            (
                f"LRS is the leakage risk score, where lower is better. The current value is **{metric(diagnosis.get('lrs_score'))}**. "
                "Leakage interpretation is limited to findings and score components stored by the deterministic diagnosis service."
            ),
            "# Stability Review",
            stability_text,
            "# Quality Assessment",
            "\n".join(finding_lines),
            "# Diagnosis Statistics Interpretation",
            "\n".join(family_lines),
            "# Variant Generator Guidance",
            "\n".join(intervention_lines),
            "# Experiment Training Handoff",
            (
                f"Use target column **{selected.get('target_column') or 'not configured'}**, primary metric "
                f"**{selected.get('primary_metric') or 'not configured'}**, validation strategy **{selected.get('validation_strategy') or 'not configured'}**, "
                f"feature selection mode **{selected.get('feature_selection_mode') or 'not configured'}**, and scaling strategy "
                f"**{selected.get('scaling_strategy') or 'not configured'}**. Treat the listed findings as constraints for experiment design before model training."
            ),
            "# Supported Claims",
            (
                "Supported by stored evidence: the selected immutable version identity, row and column counts, profile summary, "
                "MLRS/LRS values, deterministic findings, diagnosis contract interventions, and reproducibility hashes. Not supported by this report: "
                "actual model performance, causal explanations for data issues, or business/domain conclusions beyond the supplied study protocol."
            ),
            "# Required Next Actions",
            "\n".join(decision_lines),
        ])
